// examples/TodoApp/frontend-solid/src/components/Header.tsx
import { todos } from "../stores/todoStore";
import { createMemo } from "solid-js";
import "./Header.scss";

export default function Header() {
  const completedTodoCount = createMemo(() => {
    let completedCount = 0;
    for (const id of todos.ids) {
      if (todos.entities[id].completed) {
        completedCount++;
      }
    }
    return completedCount;
  });
  return (
    <div class="header">
      Todo App (#: {completedTodoCount()}/{todos.todoCount})
    </div>
  );
}

// example/TodoApp/frontend-react/src/components/Header.tsx
import { useTodos } from "../stores/todoStore.ts";

export function Header() {
  const todoCount = useTodos((state) => state.todoCount);
  const completedTodoCount = useTodos((state) => {
    let count = 0;
    for (const id of state.ids) {
      if (state.entities[id].completed) count++;
    }
    return count;
  });

  return (
    <div className={"header"}>
      Todo App (#: {completedTodoCount}/{todoCount})
    </div>
  );
}
