// examples/TodoApp/frontend-react/src/components/App.tsx
import { Header } from "./Header.tsx";
import { TodoInput } from "./TodoInput.tsx";
import { TodoList } from "./TodoList.tsx";
import { useEffect } from "react";
import { SignalConnManager } from "../api/utils/Utils.ts";
import { API } from "../api/CommandAPI.ts";

import { useTodos } from "../stores/todoStore.ts";

function App() {
  useEffect(() => {
    async function connectToAPI() {
      try {
        await API.connect();
        useTodos.getState().setupConnections();
      } catch (error) {
        console.log(error);
      }
    }

    connectToAPI().then();

    return () => {
      // Clean up --> Disconnect signals
      SignalConnManager.disconnectAll();
      API.disconnect().then();
    };
  }, []);

  return (
    <div className={"app-container"}>
      <Header />
      <TodoInput />
      <TodoList />
    </div>
  );
}

export default App;

// example/TodoApp/frontend/src/components/App.tsx
import { For, onCleanup, onMount } from "solid-js";
import { todos } from "../stores/todoStore";
import { API } from "../api/CommandAPI";
import { v4 as uuidv4 } from "uuid";
import { SignalConnManager } from "../api/utils/Utils";
import Header from "./Header";
import TodoInput from "./TodoInput";
import TodoList from "./TodoList";

export default function App() {
  onMount(async () => {
    try {
      await API.connect();
      await todos.setupConnections();
    } catch (error) {
      console.log(error);
    }
  });

  onCleanup(() => {
    // Clean up --> Disconnect signals
    SignalConnManager.disconnectAll();
    API.disconnect().then();
  });

  return (
    <div class="app-container">
      <Header />
      <TodoInput />
      <TodoList />
    </div>
  );
}
