// examples/TodoApp/frontend-solid/src/components/App.tsx
import { onCleanup, onMount } from "solid-js";
import "./App.scss";

import { todos } from "../stores/todoStore";
import { API } from "../api/CommandAPI";
import { SignalConnManager } from "../api/utils/Utils";
import Header from "./Header";
import TodoInput from "./TodoInput";
import TodoList from "./TodoList";
import { BusyDialog, busyDialog } from "./Dialogs/BusyDialog";
import { MessageBox, messageBox } from "./Dialogs/MessageBox";

export default function App() {
  onMount(async () => {
    try {
      busyDialog.show("Connecting to server...");
      await API.connect();
      await todos.setupConnections();
      busyDialog.close();
    } catch (error) {
      busyDialog.close();
      messageBox.error(`${error}`);
      console.log(error);
    }
  });

  onCleanup(() => {
    // Clean up --> Disconnect signals
    SignalConnManager.disconnectAll();
    API.disconnect().then();
  });

  return (
    <div class="appContainer">
      <Header />
      <TodoInput />
      <TodoList />
      <BusyDialog />
      <MessageBox />
    </div>
  );
}

// examples/TodoApp/frontend-react-with-preact-signals/src/components/App.tsx
import { Header } from "./Header.tsx";
import { TodoInput } from "./TodoInput.tsx";
import { TodoList } from "./TodoList.tsx";
import { useEffect } from "react";
import { SignalConnManager } from "../api/utils/Utils.ts";
import { API } from "../api/CommandAPI.ts";

import { todos } from "../stores/todoStore.ts";

function App() {
  useEffect(() => {
    async function connectToAPI() {
      try {
        await API.connect();
        await todos.setupConnections();
        // useTodos.getState().setupConnections();
      } catch (error) {
        console.log(error);
      }
    }

    connectToAPI().then();

    return () => {
      // Clean up --> Disconnect signals
      SignalConnManager.disconnectAll();
      API.disconnect().then();
    };
  }, []);

  return (
    <div className={"app-container"}>
      <Header />
      <TodoInput />
      <TodoList />
    </div>
  );
}

export default App;
