// example/TodoApp/frontend-qwik/src/components/TodoInput.tsx
import { $, component$, useContext, useSignal } from "@builder.io/qwik";
import AddCircle from "~/media/icons/AddCircle";
import { API } from "~/api/CommandAPI";
import { v4 as uuidv4 } from "uuid";
import { MessageBoxContext } from "~/components/Dialogs/MessageBox";
import { todoInput } from "~/components/TodoInput.css";

export default component$(() => {
  const inputRef = useSignal<HTMLInputElement>();
  const messageBox = useContext(MessageBoxContext);

  const onAdd = $(async () => {
    const input = inputRef.value;
    if (!input?.value.trim()) return;

    try {
      const response = await API.TodoController.add({
        id: uuidv4(),
        text: input.value.trim(),
        completed: false,
        isSelected: false,
      });

      if (response.error) throw new Error(response.error);
    } catch (e) {
      await messageBox.error(`${e}`);
    }

    input.value = "";
  });

  const onKeyUp = $(async (e: KeyboardEvent) => {
    if (e.key === "Enter") await onAdd();
  });

  return (
    <div class={todoInput}>
      <input ref={inputRef} onKeyUp$={onKeyUp} />
      <button onClick$={onAdd}>
        <AddCircle />
      </button>
    </div>
  );
});

// examples/TodoApp/frontend-react-with-preact-signals/src/components/TodoInput.tsx
import React, { useRef } from "react";
import { v4 as uuidv4 } from "uuid";
import AddCircle from "./icons/AddCircle.tsx";
import { API } from "../api/CommandAPI.ts";

export function TodoInput() {
  const input = useRef<HTMLInputElement>(null);

  async function onAdd() {
    if (!input.current?.value.trim()) return;

    const response = await API.TodoController.add({
      id: uuidv4(),
      text: input.current.value.trim(),
      completed: false,
      isSelected: false,
    });

    if (response.error) {
      console.log(response.error);
    }

    input.current.value = "";
  }

  async function onKeyUp(e: React.KeyboardEvent) {
    if (e.key === "Enter") await onAdd();
  }

  return (
    <div className={"todo-input"}>
      <input ref={input} onKeyUp={onKeyUp} />
      <button onClick={onAdd}>
        <AddCircle />
      </button>
    </div>
  );
}
