// examples/TodoApp/frontend-react-with-preact-signals/src/components/Header.tsx
import { todos } from "../stores/todoStore.ts";
import { computed } from "@preact/signals-react";

export function Header() {
  const completedTodoCount = computed(() => {
    let count = 0;
    for (const id of todos.ids) {
      if (todos.entities[id].completed) count++;
    }
    return count;
  });

  return (
    <div className={"header"}>
      Todo App (#: {completedTodoCount}/{todos.$todoCount})
    </div>
  );
}

// examples/TodoApp/frontend-solid/src/components/Header.tsx
import { todos } from "../stores/todoStore";
import { createMemo } from "solid-js";
import "./Header.scss";

export default function Header() {
  const completedTodoCount = createMemo(() => {
    let completedCount = 0;
    for (const id of todos.ids) {
      if (todos.entities[id].completed) {
        completedCount++;
      }
    }
    return completedCount;
  });
  return (
    <div class="header">
      Todo App (#: {completedTodoCount()}/{todos.todoCount})
    </div>
  );
}
