// example/TodoApp/frontend-react-with-preact-signals/src/components/Todo.tsx
import CheckMarkDone from "./icons/CheckMarkDone.tsx";
import Circle from "./icons/Circle.tsx";
import DeleteOutline from "./icons/DeleteOutline.tsx";
import React, { useEffect } from "react";
import { API } from "../api/CommandAPI.ts";
import { todos } from "../stores/todoStore.ts";

function Status({ id }: { id: string }) {
  const todo = todos.entities[id];

  const onCompletedChanged = async () => {
    const response = await API.TodoController.update({
      ...todo,
      completed: !todo.completed,
    });

    if (response.error) {
      console.log(response.error);
    }
  };

  return (
    <div className="todo-status" onClick={onCompletedChanged}>
      {todo.completed ? (
        <CheckMarkDone
          style={{ color: "green", height: "30px", width: "30px" }}
        />
      ) : (
        <Circle />
      )}
    </div>
  );
}

function Text({ id }: { id: string }) {
  const todo = todos.entities[id];
  return (
    <span
      style={{
        textDecoration: todo.completed ? "line-through" : "none",
      }}
    >
      {todo.text}
    </span>
  );
}

// Remove component
function Remove({ id }: { id: string }) {
  const onRemove = async () => {
    const response = await API.TodoController.remove(id);

    if (response.error) {
      console.log(response.error);
    }
  };

  return (
    <button onClick={onRemove}>
      <DeleteOutline />
    </button>
  );
}

export function TodoComponent({ id }: { id: string }) {
  return (
    <div className="todo">
      <Status id={id} />
      <Text id={id} />
      <Remove id={id} />
    </div>
  );
}

// Memorize the component
export const Todo = React.memo(TodoComponent);

// example/TodoApp/frontend-qwik/src/components/Todo/index.tsx
import { $, component$, useContext } from "@builder.io/qwik";
import "./style.scss";
import CheckMarkDone from "~/components/icons/CheckMarkDone";
import Circle from "~/components/icons/Circle";
import DeleteOutline from "~/components/icons/DeleteOutline";
import { TodoContext } from "~/stores/todoStore";
import { API } from "~/api/CommandAPI";

type Props = {
  id: string;
};

const Status = component$(({ id }: Props) => {
  const todos = useContext(TodoContext);

  const onCompletedChanged = $(async () => {
    const response = await API.TodoController.update({
      ...todos.entities[id],
      completed: !todos.entities[id].completed,
    });

    if (response.error) {
      console.log(response.error);
    }
  });

  return (
    <div class="status" onClick$={onCompletedChanged}>
      {todos.entities[id].completed ? (
        <CheckMarkDone
          style={{ color: "green", height: "30px", width: "30px" }}
        />
      ) : (
        <Circle />
      )}
    </div>
  );
});

const Text = component$(({ id }: Props) => {
  const todos = useContext(TodoContext);
  return (
    <span
      style={{
        textDecoration: todos.entities[id].completed ? "line-through" : "none",
      }}
    >
      {todos.entities[id].text}
    </span>
  );
});

const DeleteButton = component$(({ id }: Props) => {
  const onRemove = $(async () => {
    const response = await API.TodoController.remove(id);

    if (response.error) {
      console.log(response.error);
    }
  });

  return (
    <button onClick$={onRemove}>
      <DeleteOutline />
    </button>
  );
});
export default component$(({ id }: Props) => {
  return (
    <div class="todo">
      <Status id={id} />
      <Text id={id} />
      <DeleteButton id={id} />
    </div>
  );
});
