// examples/TodoApp/frontend-react-with-preact-signals/src/components/App.tsx
import { Header } from "./Header.tsx";
import { TodoInput } from "./TodoInput.tsx";
import { TodoList } from "./TodoList.tsx";
import { useEffect } from "react";
import { SignalConnManager } from "../api/utils/Utils.ts";
import { API } from "../api/CommandAPI.ts";

import { todos } from "../stores/todoStore.ts";

function App() {
  useEffect(() => {
    async function connectToAPI() {
      try {
        await API.connect();
        await todos.setupConnections();
        // useTodos.getState().setupConnections();
      } catch (error) {
        console.log(error);
      }
    }

    connectToAPI().then();

    return () => {
      // Clean up --> Disconnect signals
      SignalConnManager.disconnectAll();
      API.disconnect().then();
    };
  }, []);

  return (
    <div className={"app-container"}>
      <Header />
      <TodoInput />
      <TodoList />
    </div>
  );
}

export default App;

// example/TodoApp/frontend-qwik/src/components/App/index.tsx
import {
  component$,
  useContext,
  useContextProvider,
  useStore,
  useVisibleTask$,
} from "@builder.io/qwik";
import "./style.scss";
import Header from "../Header";
import TodoInput from "~/components/TodoInput";
import TodoList from "~/components/TodoList";
import { API } from "~/api/CommandAPI";
import { SignalConnManager } from "~/api/utils/Utils";
import { createTodoStore, TodoContext } from "~/stores/todoStore";

export default component$(() => {
  useContextProvider(TodoContext, useStore(createTodoStore()));
  const todos = useContext(TodoContext);

  // eslint-disable-next-line qwik/no-use-visible-task
  useVisibleTask$(async ({ cleanup }) => {
    try {
      await API.connect();
      await todos.setupConnections();
    } catch (error) {
      console.log(error);
    }

    cleanup(() => {
      // Clean up --> Disconnect signals
      SignalConnManager.disconnectAll();
      API.disconnect().then();
    });
  });

  return (
    <div class={"app-container"}>
      <Header />
      <TodoInput />
      <TodoList />
    </div>
  );
});
